#!/bin/bash
# ═══════════════════════════════════════════════════════════
#  VIMBISO — FULL LIVE DEPLOYMENT GUIDE
#  Backend: Render.com (Free)
#  Frontend: Netlify (Free)
#  DB: MongoDB Atlas (Free 512MB)
#  APK: GitHub Actions (Free)
# ═══════════════════════════════════════════════════════════

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

echo -e "${GREEN}"
echo "╔═════════════════════════════════════════════╗"
echo "║   VIMBISO AGRILINK — GO LIVE TODAY         ║"
echo "╚═════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${CYAN}STEP 1 — FREE DATABASE (MongoDB Atlas)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://mongodb.com/atlas"
echo "2. Sign up FREE → Create M0 cluster"
echo "3. Click Connect → Drivers → Copy URI"
echo "   URI looks like:"
echo "   mongodb+srv://user:pass@cluster.mongodb.net/vimbiso"
echo ""
echo -e "${CYAN}STEP 2 — FREE BACKEND (Render.com)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://render.com"
echo "2. New → Web Service → Connect GitHub repo"
echo "3. Settings:"
echo "   Root directory: backend"
echo "   Build command:  npm install"
echo "   Start command:  node server.js"
echo "4. Environment variables (add these):"
echo "   NODE_ENV=production"
echo "   MONGODB_URI=<your Atlas URI>"
echo "   JWT_SECRET=<any long random string>"
echo "   CLIENT_URL=<your Netlify URL>"
echo "5. Deploy! Your API URL will be:"
echo "   https://your-app-name.onrender.com"
echo ""
echo -e "${CYAN}STEP 3 — FREE FRONTEND (Netlify)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://netlify.com"
echo "2. New site → Import from GitHub"
echo "3. Settings:"
echo "   Base directory:   frontend"
echo "   Build command:    npm install && npm run build"
echo "   Publish directory:frontend/dist"
echo "4. Environment variable:"
echo "   VITE_API_URL=https://your-backend.onrender.com"
echo "5. Deploy! Your app URL will be:"
echo "   https://vimbiso-agrilink.netlify.app"
echo ""
echo -e "${CYAN}STEP 4 — APK (GitHub Actions — Auto Build)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Run: bash GITHUB_APK.sh"
echo "2. Wait 8 minutes"
echo "3. Download APK from GitHub Releases"
echo "4. Share the APK download link with users"
echo ""
echo -e "${CYAN}STEP 5 — SEED DEMO DATA${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After backend is live, run once:"
echo "  curl https://your-backend.onrender.com/api/health"
echo "  (Then trigger seed via Render shell)"
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════"
echo " EVERYTHING IS FREE. No credit card needed."
echo " Total cost: $0/month for the demo phase"
echo -e "═══════════════════════════════════════════════${NC}"
echo ""
echo "Questions? All links:"
echo "  Atlas:   https://mongodb.com/atlas"
echo "  Render:  https://render.com"
echo "  Netlify: https://netlify.com"
echo "  GitHub:  https://github.com"
