name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install & Build
        run: |
          cd frontend
          npm install
          cd android
          chmod +x gradlew
         ./gradlew assembleRelease --no-daemon
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vimbiso-apk
          path: frontend/android/app/build/outputs/apk/release/*.apk
